#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Take advantage of the Pressflow 7 helper cartridge to inject MySQL, etc.
if [ ! -z $OPENSHIFT_PRESSFLOW7_DIR ]; then
  $OPENSHIFT_PRESSFLOW7_DIR/bin/update-pressflow-settings
fi

# Set the apc.shm_size to 160 megabytes if it has not yet been sent.
[[ -z $OPENSHIFT_PHP_APC_SHM_SIZE ]] && {
  echo "160M" > ~/.env/user_vars/OPENSHIFT_PHP_APC_SHM_SIZE
  gear stop php
  gear start php
}
